[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
stacking_program = "Ftn6jkHD4MSJDf8QFqP9jjzCyxtHzKbTCtMwTne1XDbm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/wild/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
